version: "3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - C:\s7InfluxDB:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - C:\s7InfluxDB:/var/lib/influxdb2:rw
      - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment:
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ucs
      - DOCKER_INFLUXDB_INIT_PASSWORD=Test1234!
      - DOCKER_INFLUXDB_INIT_ORG=UCS
      - DOCKER_INFLUXDB_INIT_BUCKET=PlcData
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Test1234!
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - C:\s7InfluxDB\telegraf\telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8094:8094"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=UCS
      - DOCKER_INFLUXDB_INIT_BUCKET=PlcData
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Test1234!
    depends_on:
      - influxdb_cli
volumes:
  influxdb2:
